default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: memoly_api_db_development

  queue:
    database: memoly_api_queue_development
    migrations_paths: db/queue_migrate


test:
  <<: *default
  database: memoly_api_db_test

production:
  primary: &primary_production
    <<: *default
    username: ENV.fetch("DB_USERNAME")
    password: ENV.fetch("DB_PASSWORD")
    database: memoly_api_db_production

  cable:
    <<: *primary_production
    database: memoly_api_cable_production
    migrations_paths: db/cable_migrate

  queue:
    <<: *primary_production
    database: memoly_api_queue_production
    migrations_paths: db/queue_migrate

  cache:
    <<: *primary_production
    database: memoly_api_cache_production
    migrations_paths: db/cache_migrate