default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: memoly_api_db_development

test:
  <<: *default
  database: memoly_api_db_test

production:
  primary:
    <<: *default
    database: memoly_api_db_production

  cable:
    <<: *default
    database: memoly_api_db_production

  queue:
    <<: *default
    database: memoly_api_db_production

  cache:
    <<: *default
    database: memoly_api_db_production