apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memoly-api.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "memoly-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "memoly-api.name" . }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "⏳ Waiting for PostgreSQL..."
              until nc -z {{ .Values.postgresqlHost }} 5432; do
                echo "❌ PostgreSQL not ready, retrying in 2s..."
                sleep 2
              done
              echo "✅ PostgreSQL is ready."
      containers:
        - name: memoly-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "memoly-api.fullname" . }}  