apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "memoly-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: memoly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "memoly-api.fullname" . }}
                port:
                  number: 3000