apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memoly-api.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  POSTMARK_API_KEY: {{ .Values.postmark.apiKey | quote }}
  RAILS_MASTER_KEY: {{ .Values.rails.masterKey | quote }}
