apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoly-sidekiq
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoly-sidekiq
  template:
    metadata:
      labels:
        app: memoly-sidekiq
    spec:
      containers:
        - name: sidekiq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "sidekiq"]
          env:
            - name: RAILS_ENV
              value: "production"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "memoly-api.fullname" . }}
                  key: REDIS_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "memoly-api.fullname" . }}
                  key: DATABASE_URL
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "memoly-api.fullname" . }}
                  key: RAILS_MASTER_KEY